/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ATable: typeof import('ant-design-vue/es')['Table']
    copy: typeof import('./src/components/List copy.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    PokemonList: typeof import('./src/components/PokemonList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableList: typeof import('./src/components/TableList.vue')['default']
    Teste: typeof import('./src/components/Teste.vue')['default']
  }
}
